source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '>= 3.2.0'

gem 'rails', '~> 8.1.0'
gem 'puma', '~> 7.2'
gem 'bootsnap', '>= 1.21.0', require: false
gem 'redis', '~> 5.4'

# CORS for React Native
gem 'rack-cors'

group :development, :test do
  gem 'debug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'sqlite3', '~> 2.0'
end

group :development do
  gem 'listen', '~> 3.9'
end
